export const express = [
  {"company": "韵达快递", "code": "yunda"},
  {"company": "百世快递", "code": "huitongkuaidi"},
  {"company": "邮政快递包裹", "code": "youzhengguonei"},
  {"company": "申通快递", "code": "shentong"},
  {"company": "圆通速递", "code": "yuantong"},
  {"company": "中通快递", "code": "zhongtong"},
  {"company": "顺丰速运", "code": "shunfeng"},
  {"company": "京东物流", "code": "jd"},
  {"company": "EMS", "code": "ems"},
  {"company": "国际包裹", "code": "youzhengguoji"},
  {"company": "天天快递", "code": "tiantian"},
  {"company": "EMS-国际件", "code": "emsguoji"},
  {"company": "德邦", "code": "debangwuliu"},
  {"company": "EMS-国际件-英文", "code": "emsinten"},
  {"company": "EMS-英文", "code": "emsen"},
  {"company": "DHL-全球件", "code": "dhlen"},
  {"company": "优速物流", "code": "youshuwuliu"},
  {"company": "宅急送", "code": "zhaijisong"},
  {"company": "百世快运", "code": "baishiwuliu"},
  {"company": "品骏快递", "code": "pjbest"},
  {"company": "澳大利亚(Australia Post)", "code": "auspost"},
  {"company": "DHL-中国件", "code": "dhl"},
  {"company": "递四方", "code": "disifang"},
  {"company": "USPS", "code": "usps"},
  {"company": "FedEx-国际件", "code": "fedex"},
  {"company": "德邦快递", "code": "debangkuaidi"},
  {"company": "跨越速运", "code": "kuayue"},
  {"company": "EWE全球快递", "code": "ewe"},
  {"company": "日本（Japan Post）", "code": "japanposten"},
  {"company": "澳邮中国快运", "code": "auexpress"},
  {"company": "安能快运", "code": "annengwuliu"},
  {"company": "邮政国内", "code": "yzguonei"},
  {"company": "速尔快递", "code": "suer"},
  {"company": "中通快运", "code": "zhongtongkuaiyun"},
  {"company": "程光快递", "code": "flyway"},
  {"company": "韵达快运", "code": "yundakuaiyun"},
  {"company": "威盛快递", "code": "wherexpess"},
  {"company": "广东邮政", "code": "guangdongyouzhengwuliu"},
  {"company": "全峰快递", "code": "quanfengkuaidi"},
  {"company": "UPS-全球件", "code": "upsen"},
  {"company": "UPS", "code": "ups"},
  {"company": "优邦速运", "code": "ubonex"},
  {"company": "Aramex", "code": "aramex"},
  {"company": "FedEx-美国件", "code": "fedexus"},
  {"company": "中通（带电话）", "code": "zhongtongphone"},
  {"company": "南方传媒物流", "code": "ndwl"},
  {"company": "日日顺物流", "code": "rrs"},
  {"company": "国通快递", "code": "guotongkuaidi"},
  {"company": "宇鑫物流", "code": "yuxinwuliu"},
  {"company": "美快国际物流", "code": "meiquick"},
  {"company": "中国香港(HongKong Post)", "code": "hkpost"},
  {"company": "EMS包裹", "code": "emsbg"},
  {"company": "COE", "code": "coe"},
  {"company": "中邮物流", "code": "zhongyouwuliu"},
  {"company": "邮政标准快递", "code": "youzhengbk"},
  {"company": "转运四方", "code": "zhuanyunsifang"},
  {"company": "万象物流", "code": "wanxiangwuliu"},
  {"company": "易达通快递", "code": "qexpress"},
  {"company": "TNT", "code": "tnt"},
  {"company": "DHL-德国件（DHL Deutschland）", "code": "dhlde"},
  {"company": "富腾达国际货运", "code": "ftd"},
  {"company": "澳世速递", "code": "ausexpress"},
  {"company": "龙邦速递", "code": "longbanwuliu"},
  {"company": "苏宁物流", "code": "suning"},
  {"company": "三象速递", "code": "sxexpress"},
  {"company": "同城快寄", "code": "shpost"},
  {"company": "快捷速递", "code": "kuaijiesudi"},
  {"company": "D速快递", "code": "dsukuaidi"},
  {"company": "AAE-中国件", "code": "aae"},
  {"company": "联昊通", "code": "lianhaowuliu"},
  {"company": "特急送", "code": "lntjs"},
  {"company": "壹米滴答", "code": "yimidida"},
  {"company": "TransRush", "code": "transrush"},
  {"company": "全一快递", "code": "quanyikuaidi"},
  {"company": "圆通快运", "code": "yuantongkuaiyun"},
  {"company": "联合速运", "code": "unitedex"},
  {"company": "集先锋快递", "code": "jxfex"},
  {"company": "联邦快递", "code": "lianbangkuaidi"},
  {"company": "安世通快递", "code": "astexpress"},
  {"company": "安得物流", "code": "annto"},
  {"company": "Superb Grace", "code": "superb"},
  {"company": "宅急便", "code": "zhaijibian"},
  {"company": "UEQ快递", "code": "ueq"},
  {"company": "斑马物流", "code": "banma"},
  {"company": "新邦物流", "code": "xinbangwuliu"},
  {"company": "Xlobo贝海国际", "code": "xlobo"},
  {"company": "中速快递", "code": "zhongsukuaidi"},
  {"company": "信丰物流", "code": "xinfengwuliu"},
  {"company": "申通国际", "code": "stosolution"},
  {"company": "红马甲物流", "code": "sxhongmajia"},
  {"company": "优速通达", "code": "yousutongda"},
  {"company": "新顺丰（NSF）", "code": "nsf"},
  {"company": "欧亚专线", "code": "euasia"},
  {"company": "光线速递", "code": "gxwl"},
  {"company": "佳吉快运", "code": "jiajiwuliu"},
  {"company": "申通快运", "code": "stoe56"},
  {"company": "OnTrac", "code": "ontrac"},
  {"company": "速必达", "code": "subida"},
  {"company": "美国云达", "code": "yundaexus"},
  {"company": "承诺达", "code": "ytchengnuoda"},
  {"company": "港快速递", "code": "gdkd"},
  {"company": "恒路物流", "code": "hengluwuliu"},
  {"company": "速达通", "code": "sdto"},
  {"company": "疯狂快递", "code": "crazyexpress"},
  {"company": "英国大包、EMS（Parcel Force）", "code": "parcelforce"},
  {"company": "景顺物流", "code": "jingshun"},
  {"company": "安鲜达", "code": "exfresh"},
  {"company": "中铁快运", "code": "zhongtiewuliu"},
  {"company": "TNT-全球件", "code": "tnten"},
  {"company": "京广速递", "code": "jinguangsudikuaijian"},
  {"company": "荷兰邮政-中文(PostNL international registered mail)", "code": "postnlcn"},
  {"company": "OCS", "code": "ocs"},
  {"company": "中翼国际物流", "code": "chnexp"},
  {"company": "美通", "code": "valueway"},
  {"company": "洋包裹", "code": "yangbaoguo"},
  {"company": "CNAIR", "code": "cnair"},
  {"company": "中粮鲜到家物流", "code": "zlxdjwl"},
  {"company": "中通国际", "code": "zhongtongguoji"},
  {"company": "中外运", "code": "esinotrans"},
  {"company": "运通中港", "code": "yuntongkuaidi"},
  {"company": "易客满", "code": "ecmscn"},
  {"company": "俄罗斯邮政(Russian Post)", "code": "pochta"},
  {"company": "长江国际速递", "code": "changjiang"},
  {"company": "中环快递", "code": "zhonghuan"},
  {"company": "台湾（中华邮政）", "code": "postserv"},
  {"company": "盛辉物流", "code": "shenghuiwuliu"},
  {"company": "出口易", "code": "chukou1"},
  {"company": "DPEX", "code": "dpex"},
  {"company": "Fedex-国际件-中文", "code": "fedexcn"},
  {"company": "DPD UK", "code": "dpduk"},
  {"company": "CNPEX中邮快递", "code": "cnpex"},
  {"company": "e直运", "code": "edtexpress"},
  {"company": "联合快递", "code": "gslhkd"},
  {"company": "加拿大(Canada Post)", "code": "canpost"},
  {"company": "迅速快递", "code": "xunsuexpress"},
  {"company": "保加利亚（Bulgarian Posts）", "code": "bulgarian"},
  {"company": "Toll", "code": "dpexen"},
  {"company": "优莎速运", "code": "eusacn"},
  {"company": "程光快递", "code": "chengguangkuaidi"},
  {"company": "嘉里大通", "code": "jialidatong"},
  {"company": "百事亨通", "code": "bsht"},
  {"company": "新杰物流", "code": "sunjex"},
  {"company": "中铁物流", "code": "ztky"},
  {"company": "加运美", "code": "jiayunmeiwuliu"},
  {"company": "安迅物流", "code": "anxl"},
  {"company": "方舟速递", "code": "arkexpress"},
  {"company": "极地快递", "code": "polarexpress"},
  {"company": "SYNSHIP快递", "code": "synship"},
  {"company": "环球速运", "code": "huanqiu"},
  {"company": "美西快递", "code": "meixi"},
  {"company": "美国快递", "code": "meiguokuaidi"},
  {"company": "英国小包（Royal Mail）", "code": "royalmail"},
  {"company": "优联吉运", "code": "uluckex"},
  {"company": "优优速递", "code": "youyou"},
  {"company": "新加坡小包(Singapore Post)", "code": "singpost"},
  {"company": "日本郵便", "code": "japanpost"},
  {"company": "如风达", "code": "rufengda"},
  {"company": "亚风速递", "code": "yafengsudi"},
  {"company": "比利时（Bpost）", "code": "bpost"},
  {"company": "ZTE中兴物流", "code": "zteexpress"},
  {"company": "韩国（Korea Post）", "code": "koreapost"},
  {"company": "蓝天快递", "code": "blueskyexpress"},
  {"company": "City-Link", "code": "citylink"},
  {"company": "恒宇运通", "code": "hyytes"},
  {"company": "瑞士邮政", "code": "swisspostcn"},
  {"company": "中国澳门(Macau Post)", "code": "macao"},
  {"company": "比利时国际(Bpost international)", "code": "bpostinter"},
  {"company": "捷安达", "code": "jieanda"},
  {"company": "大田物流", "code": "datianwuliu"},
  {"company": "泛捷国际速递", "code": "epanex"},
  {"company": "荷兰邮政(PostNL international registered mail)", "code": "postnl"},
  {"company": "增速跨境 ", "code": "zyzoom"},
  {"company": "瑞士(Swiss Post)", "code": "swisspost"},
  {"company": "TNT UK", "code": "tntuk"},
  {"company": "锦程快递", "code": "hrex"},
  {"company": "CNE", "code": "cnexps"},
  {"company": "全联速运", "code": "guexp"},
  {"company": "德国(Deutsche Post)", "code": "deutschepost"},
  {"company": "宏递快运", "code": "hd"},
  {"company": "小熊物流", "code": "littlebearbear"},
  {"company": "DPD", "code": "dpd"},
  {"company": "鼎润物流", "code": "la911"},
  {"company": "晟邦物流", "code": "nanjingshengbang"},
  {"company": "安能快递", "code": "ane66"},
  {"company": "中国香港(HongKong Post)英文", "code": "hkposten"},
  {"company": "秦远物流", "code": "qinyuan"},
  {"company": "顺丰-繁体", "code": "shunfenghk"},
  {"company": "顺丰-美国件", "code": "shunfengen"},
  {"company": "众川国际", "code": "zhongchuan"},
  {"company": "法国(La Poste)", "code": "csuivi"},
  {"company": "英国邮政小包", "code": "royalmailcn"},
  {"company": "家家通快递", "code": "newsway"},
  {"company": "汇通天下物流", "code": "httx56"},
  {"company": "驿扬国际速运", "code": "iyoungspeed"},
  {"company": "Fastway Ireland", "code": "fastway"},
  {"company": "TNT Australia", "code": "tntau"},
  {"company": "盛丰物流", "code": "shengfengwuliu"},
  {"company": "瑞典（Sweden Post）", "code": "ruidianyouzheng"},
  {"company": "圆通国际", "code": "yuantongguoji"},
  {"company": "顺心捷达", "code": "sxjdfreight"},
  {"company": "合众速递(UCS）", "code": "ucs"},
  {"company": "法国小包（colissimo）", "code": "colissimo"},
  {"company": "广东速腾物流", "code": "suteng"},
  {"company": "速递中国", "code": "sendtochina"},
  {"company": "西翼物流", "code": "westwing"},
  {"company": "源安达", "code": "yuananda"},
  {"company": "Hermes", "code": "hermes"},
  {"company": "安达速递", "code": "adapost"},
  {"company": "荷兰速递(Nederland Post)", "code": "nederlandpost"},
  {"company": "远成物流", "code": "yuanchengwuliu"},
  {"company": "尚橙物流", "code": "shangcheng"},
  {"company": "蓝天快递", "code": "lantiankuaidi"},
  {"company": "货运皇", "code": "kingfreight"},
  {"company": "意大利(Poste Italiane)", "code": "italiane"},
  {"company": "八达通", "code": "bdatong"},
  {"company": "陆本速递 LUBEN EXPRESS", "code": "luben"},
  {"company": "USPSCN", "code": "uspscn"},
  {"company": "西班牙(Correos de Espa?a)", "code": "correosdees"},
  {"company": "TST速运通", "code": "tstexp"},
  {"company": "联运通物流", "code": "szuem"},
  {"company": "考拉速递", "code": "koalaexp"},
  {"company": "PCA Express", "code": "pcaexpress"},
  {"company": "澳天速运", "code": "aotsd"},
  {"company": "天翼快递", "code": "tykd"},
  {"company": "佳成快递 ", "code": "jiacheng"},
  {"company": "平安达腾飞", "code": "pingandatengfei"},
  {"company": "荷兰包裹(PostNL International Parcels)", "code": "postnlpacle"},
  {"company": "金岸物流", "code": "jinan"},
  {"company": "Asendia USA", "code": "asendiausa"},
  {"company": "久久物流", "code": "jiujiuwl"},
  {"company": "比利时(Belgium Post)", "code": "belgiumpost"},
  {"company": "星云速递", "code": "nebuex"},
  {"company": "能达速递", "code": "ganzhongnengda"},
  {"company": "远成快运", "code": "ycgky"},
  {"company": "CCES/国通快递", "code": "cces"},
  {"company": "加州猫速递", "code": "jiazhoumao"},
  {"company": "转运中国", "code": "uszcn"},
  {"company": "速通物流", "code": "sutongwuliu"},
  {"company": "澳德物流", "code": "auod"},
  {"company": "万家康物流", "code": "wjkwl"},
  {"company": "佳怡物流", "code": "jiayiwuliu"},
  {"company": "安信达", "code": "anxindakuaixi"},
  {"company": "飞洋快递", "code": "shipgce"},
  {"company": "德中快递", "code": "decnlh"},
  {"company": "澳世速递", "code": "aus"},
  {"company": "新西兰（New Zealand Post）", "code": "newzealand"},
  {"company": "偌亚奥国际快递", "code": "nuoyaao"},
  {"company": "英超物流", "code": "yingchao"},
  {"company": "成都立即送", "code": "lijisong"},
  {"company": "加运美速递", "code": "jym56"},
  {"company": "佐川急便", "code": "sagawa"},
  {"company": "增益速递", "code": "zengyisudi"},
  {"company": "法国大包、EMS-法文（Chronopost France）", "code": "chronopostfra"},
  {"company": "玥玛速运", "code": "yue777"},
  {"company": "百腾物流", "code": "baitengwuliu"},
  {"company": "卓志速运", "code": "chinaicip"},
  {"company": "中澳速递", "code": "cnausu"},
  {"company": "韩国邮政", "code": "koreapostcn"},
  {"company": "星空国际", "code": "wlwex"},
  {"company": "民航快递", "code": "minghangkuaidi"},
  {"company": "中技物流", "code": "zhongjiwuliu"},
  {"company": "易达通", "code": "yidatong"},
  {"company": "优海国际速递", "code": "uhi"},
  {"company": "百千诚物流", "code": "bqcwl"},
  {"company": "速派快递(FastGo)", "code": "fastgo"},
  {"company": "跨境直邮通", "code": "kjde"},
  {"company": "FQ狂派速递", "code": "freakyquick"},
  {"company": "快服务", "code": "kfwnet"},
  {"company": "DHL Benelux", "code": "dhlbenelux"},
  {"company": "环国运物流", "code": "hgy56"},
  {"company": "AOL澳通速递", "code": "aolau"},
  {"company": "澳通华人物流", "code": "cllexpress"},
  {"company": "Newgistics", "code": "newgistics"},
  {"company": "印度(India Post)", "code": "india"},
  {"company": "EASY EXPRESS", "code": "easyexpress"},
  {"company": "贝业物流", "code": "boyol"},
  {"company": "EFS Post（平安快递）", "code": "efs"},
  {"company": "黑猫速运", "code": "heimao56"},
  {"company": "乌克兰邮政包裹", "code": "ukrpostcn"},
  {"company": "美国申通", "code": "stoexpress"},
  {"company": "宇佳物流", "code": "yujiawl"},
  {"company": "锋鸟物流", "code": "beebird"},
  {"company": "上海航瑞货运", "code": "hangrui"},
  {"company": "景光物流", "code": "jgwl"},
  {"company": "百福东方", "code": "baifudongfang"},
  {"company": "万家物流", "code": "wanjiawuliu"},
  {"company": "穗佳物流", "code": "suijiawuliu"},
  {"company": "马来西亚小包（Malaysia Post(Registered)）", "code": "malaysiapost"},
  {"company": "启辰国际速递", "code": "qichen"},
  {"company": "易达国际速递", "code": "eta100"},
  {"company": "堡昕德速递", "code": "bosind"},
  {"company": "泰国（Thailand Thai Post）", "code": "thailand"},
  {"company": "鸿泰物流", "code": "hnht56"},
  {"company": "骏绅物流", "code": "jsexpress"},
  {"company": "airpak expresss", "code": "airpak"},
  {"company": "韩国邮政韩文", "code": "koreapostkr"},
  {"company": "amazon-国际订单", "code": "amusorder"},
  {"company": "奔腾物流", "code": "benteng"},
  {"company": "邦通国际", "code": "comexpress"},
  {"company": "签收快递", "code": "signedexpress"},
  {"company": "BHT", "code": "bht"},
  {"company": "佰麒快递", "code": "beckygo"},
  {"company": "如家国际快递", "code": "homecourier"},
  {"company": "中邮速递", "code": "wondersyd"},
  {"company": "澳速物流", "code": "aosu"},
  {"company": "乐天速递", "code": "ltexp"},
  {"company": "丰程物流", "code": "sccod"},
  {"company": "马来西亚大包、EMS（Malaysia Post(parcel,EMS)）", "code": "malaysiaems"},
  {"company": "共速达", "code": "gongsuda"},
  {"company": "天翼物流", "code": "tywl99"},
  {"company": "北京EMS", "code": "bjemstckj"},
  {"company": "波兰小包(Poczta Polska)", "code": "emonitoring"},
  {"company": "宏品物流", "code": "hongpinwuliu"},
  {"company": "金大物流", "code": "jindawuliu"},
  {"company": "丹麦(Post Denmark)", "code": "postdanmarken"},
  {"company": "商海德物流", "code": "shd56"},
  {"company": "track-parcel", "code": "trackparcel"},
  {"company": "迅达速递", "code": "xdexpress"},
  {"company": "青岛安捷快递", "code": "anjiekuaidi"},
  {"company": "泰进物流", "code": "taijin"},
  {"company": "捷邦物流", "code": "jieborne"},
  {"company": "五六快运", "code": "wuliuky"},
  {"company": "CJ物流", "code": "doortodoor"},
  {"company": "运通中港快递", "code": "ytkd"},
  {"company": "加拿大邮政", "code": "canpostfr"},
  {"company": "中国香港环球快运", "code": "huanqiuabc"},
  {"company": "全际通", "code": "quanjitong"},
  {"company": "全日通", "code": "quanritongkuaidi"},
  {"company": "易境达国际物流", "code": "uscbexpress"},
  {"company": "中外运速递", "code": "zhongwaiyun"},
  {"company": "爱尔兰(An Post)", "code": "anposten"},
  {"company": "奥地利(Austrian Post)", "code": "austria"},
  {"company": "邦送物流", "code": "bangsongwuliu"},
  {"company": "传喜物流", "code": "chuanxiwuliu"},
  {"company": "捷特快递", "code": "jietekuaidi"},
  {"company": "深圳德创物流", "code": "dechuangwuliu"},
  {"company": "格鲁吉亚(Georgian Pos）", "code": "georgianpost"},
  {"company": "海米派物流", "code": "haimibuy"},
  {"company": "华企快运", "code": "huaqikuaiyun"},
  {"company": "新元国际", "code": "xynyc"},
  {"company": "龙邦物流", "code": "lbex"},
  {"company": "華信物流WTO", "code": "logistics"},
  {"company": "明亮物流", "code": "mingliangwuliu"},
  {"company": "秦邦快运", "code": "qbexpress"},
  {"company": "林道国际快递", "code": "shlindao"},
  {"company": "中运全速", "code": "topspeedex"},
  {"company": "YODEL", "code": "yodel"},
  {"company": "苏通快运", "code": "zjstky"},
  {"company": "中联速递", "code": "auvanda"},
  {"company": "德坤物流", "code": "dekuncn"},
  {"company": "土耳其", "code": "ptt"},
  {"company": "驭丰速运", "code": "yfsuyun"},
  {"company": "中天万运", "code": "zhongtianwanyun"},
  {"company": "创一快递", "code": "chuangyi"},
  {"company": "大洋物流", "code": "dayangwuliu"},
  {"company": "飞豹快递", "code": "feibaokuaidi"},
  {"company": "丰通快运", "code": "ftky365"},
  {"company": "GHT物流", "code": "ghtexpress"},
  {"company": "天天快物流", "code": "guoeryue"},
  {"company": "上大物流", "code": "shangda"},
  {"company": "信联通", "code": "sinatone"},
  {"company": "顺达快递", "code": "sundarexpress"},
  {"company": "TRAKPAK", "code": "trakpak"},
  {"company": "威时沛运货运", "code": "wtdchina"},
  {"company": "全球快运", "code": "abcglobal"},
  {"company": "彪记快递", "code": "biaojikuaidi"},
  {"company": "E跨通", "code": "ecallturn"},
  {"company": "德尚国际速递", "code": "gslexpress"},
  {"company": "骏丰国际速递", "code": "junfengguoji"},
  {"company": "爱沙尼亚(Eesti Post)", "code": "omniva"},
  {"company": "新加坡EMS、大包(Singapore Speedpost)", "code": "speedpost"},
  {"company": "纵通速运", "code": "ynztsy"},
  {"company": "越丰物流", "code": "yuefengwuliu"},
  {"company": "蜜蜂速递", "code": "bee001"},
  {"company": "城际速递", "code": "chengjisudi"},
  {"company": "林道国际快递-英文", "code": "ldxpres"},
  {"company": "腾达速递", "code": "nntengda"},
  {"company": "渥途国际速运", "code": "wotu"},
  {"company": "美国汉邦快递", "code": "aplus100"},
  {"company": "捷克（?eská po?ta）", "code": "ceskaposta"},
  {"company": "长宇物流", "code": "changyuwuliu"},
  {"company": "哥斯达黎加(Correos de Costa Rica)", "code": "correos"},
  {"company": "高铁快运", "code": "gaotieex"},
  {"company": "鸿讯物流", "code": "hongxun"},
  {"company": "海淘物流", "code": "ht22"},
  {"company": "Landmark Global", "code": "landmarkglobal"},
  {"company": "龙飞祥快递", "code": "longfx"},
  {"company": "新亚物流", "code": "nalexpress"},
  {"company": "澳洲飞跃物流", "code": "rlgaus"},
  {"company": "三态速递", "code": "santaisudi"},
  {"company": "阳光快递", "code": "shiningexpress"},
  {"company": "顺捷丰达", "code": "shunjiefengda"},
  {"company": "深圳邮政", "code": "szyouzheng"},
  {"company": "越南EMS(VNPost Express)", "code": "vnpost"},
  {"company": "亚马逊中国", "code": "yamaxunwuliu"},
  {"company": "一站通快递", "code": "zgyzt"},
  {"company": "布谷鸟速递", "code": "cuckooexpess"},
  {"company": "希腊EMS（ELTA Courier）", "code": "eltahell"},
  {"company": "飞康达", "code": "feikangda"},
  {"company": "匈牙利（Magyar Posta）", "code": "hungary"},
  {"company": "拉脱维亚(Latvijas Pasts)", "code": "latvia"},
  {"company": "昂威物流", "code": "onway"},
  {"company": "葡萄牙（Portugal CTT）", "code": "portugalctt"},
  {"company": "全速物流", "code": "quansu"},
  {"company": "万庚国际速递", "code": "vangenexpress"},
  {"company": "越中国际物流", "code": "vctrans"},
  {"company": "鑫通宝物流", "code": "xtb"},
  {"company": "一邦速递", "code": "yibangwuliu"},
  {"company": "A2U速递", "code": "a2u"},
  {"company": "C&C国际速递", "code": "cncexp"},
  {"company": "阿联酋(Emirates Post)", "code": "emirates"},
  {"company": "凡宇快递", "code": "fanyukuaidi"},
  {"company": "丰客物流", "code": "fecobv"},
  {"company": "FedEx-英国件（FedEx UK)", "code": "fedexuk"},
  {"company": "飞远配送", "code": "feiyuanvipshop"},
  {"company": "华美快递", "code": "hmus"},
  {"company": "毛里求斯(Mauritius Post)", "code": "mauritius"},
  {"company": "PostElbe", "code": "postelbe"},
  {"company": "十方通物流", "code": "sfift"},
  {"company": "海龟国际快递", "code": "turtle"},
  {"company": "铁中快运", "code": "tzky"},
  {"company": "祥龙运通物流", "code": "xianglongyuntong"},
  {"company": "御风速运", "code": "yufeng"},
  {"company": "德国雄鹰速递", "code": "adlerlogi"},
  {"company": "捷记方舟", "code": "ajexpress"},
  {"company": "心怡物流", "code": "alog"},
  {"company": "百通物流", "code": "buytong"},
  {"company": "喀麦隆(CAMPOST)", "code": "cameroon"},
  {"company": "能装能送", "code": "canhold"},
  {"company": "河南次晨达", "code": "ccd"},
  {"company": "CHS中环国际快递", "code": "chszhonghuanguoji"},
  {"company": "叮咚澳洲转运", "code": "dindon"},
  {"company": "成都东骏物流", "code": "dongjun"},
  {"company": "DPD Germany", "code": "dpdgermany"},
  {"company": "DPD Poland", "code": "dpdpoland"},
  {"company": "俄顺达", "code": "eshunda"},
  {"company": "7号速递", "code": "express7th"},
  {"company": "芬兰(Itella Posti Oy)", "code": "finland"},
  {"company": "GLS", "code": "gls"},
  {"company": "华航快递", "code": "hzpl"},
  {"company": "印度尼西亚EMS(Pos Indonesia-EMS)", "code": "indonesia"},
  {"company": "佳吉快递", "code": "jiajikuaidi"},
  {"company": "急先达", "code": "jixianda"},
  {"company": "四川快优达速递", "code": "kuaiyouda"},
  {"company": "乐捷递", "code": "lejiedi"},
  {"company": "恒通快递", "code": "lqht"},
  {"company": "亚欧专线", "code": "nlebv"},
  {"company": "挪威（Posten Norge）", "code": "postennorge"},
  {"company": "日昱物流", "code": "riyuwuliu"},
  {"company": "南非（South African Post Office）", "code": "southafrican"},
  {"company": "春风物流", "code": "spring56"},
  {"company": "新元快递", "code": "xingyuankuaidi"},
  {"company": "云达通", "code": "ydglobe"},
  {"company": "远航国际快运", "code": "yuanhhk"},
  {"company": "邮客全球速递", "code": "yyox"},
  {"company": "一智通", "code": "1ziton"},
  {"company": "ABF", "code": "abf"},
  {"company": "明大快递", "code": "adaexpress"},
  {"company": "安达信", "code": "advancing"},
  {"company": "阿尔巴尼亚(Posta shqipatre)", "code": "albania"},
  {"company": "安捷物流", "code": "anjie88"},
  {"company": "澳货通", "code": "auex"},
  {"company": "城际快递", "code": "chengji"},
  {"company": "智利(Correos Chile)", "code": "chile"},
  {"company": "CE易欧通国际速递", "code": "cloudexpress"},
  {"company": "乌拉圭（Correo Uruguayo）", "code": "correo"},
  {"company": "大道物流", "code": "dadaoex"},
  {"company": "泛远国际物流", "code": "farlogistis"},
  {"company": "FOX国际快递", "code": "fox"},
  {"company": "GSM", "code": "gsm"},
  {"company": "GTS快递", "code": "gts"},
  {"company": "海红网送", "code": "haihongwangsong"},
  {"company": "海外环球", "code": "haiwaihuanqiu"},
  {"company": "Hi淘易快递", "code": "hitaoe"},
  {"company": "康力物流", "code": "kangliwuliu"},
  {"company": "6LS EXPRESS", "code": "lsexpress"},
  {"company": "尼日利亚(Nigerian Postal)", "code": "nigerianpost"},
  {"company": "新西兰中通", "code": "nzzto"},
  {"company": "千顺快递", "code": "qskdyxgs"},
  {"company": "全晨快递", "code": "quanchenkuaidi"},
  {"company": "全川物流", "code": "quanchuan56"},
  {"company": "全速通", "code": "quansutong"},
  {"company": "叙利亚(Syrian Post)", "code": "republic"},
  {"company": "赛澳递", "code": "saiaodi"},
  {"company": "赛澳递for买卖宝", "code": "saiaodimmb"},
  {"company": "澳丰速递", "code": "sfau"},
  {"company": "商桥物流", "code": "shangqiao56"},
  {"company": "圣安物流", "code": "shenganwuliu"},
  {"company": "顺通快递", "code": "stkd"},
  {"company": "郑州速捷", "code": "sujievip"},
  {"company": "天越物流", "code": "surpassgo"},
  {"company": "速通物流", "code": "sut56"},
  {"company": "株式会社T.M.G", "code": "tmg"},
  {"company": "UEX国际物流", "code": "uex"},
  {"company": "乌兹别克斯坦(Post of Uzbekistan)", "code": "uzbekistan"},
  {"company": "鑫远东速运", "code": "xyd666"},
  {"company": "银捷速递", "code": "yinjiesudi"},
  {"company": "易欧洲国际物流", "code": "yiouzhou"},
  {"company": "永昌物流", "code": "yongchangwuliu"},
  {"company": "友家速递", "code": "youjia"},
  {"company": "远盾物流", "code": "yuandun"},
  {"company": "德国云快递", "code": "yunexpress"},
  {"company": "运通速运", "code": "yuntong"},
  {"company": "至诚通达快递", "code": "zhichengtongda"},
  {"company": "泰捷达国际物流", "code": "ztjieda"},
  {"company": "五六快运", "code": "56kuaiyun"},
  {"company": "安达易国际速递", "code": "adiexpress"},
  {"company": "ADP国际快递", "code": "adp"},
  {"company": "航空快递", "code": "airgtc"},
  {"company": "新干线快递", "code": "anlexpress"},
  {"company": "Aplus物流", "code": "aplusex"},
  {"company": "皮牙子快递", "code": "bazirim"},
  {"company": "伯利兹(Belize Postal)", "code": "belize"},
  {"company": "巴西(Brazil Post/Correios)", "code": "brazilposten"},
  {"company": "展勤快递", "code": "byht"},
  {"company": "柬埔寨(Cambodia Post)", "code": "cambodia"},
  {"company": "CDEK", "code": "cdek"},
  {"company": "成达国际速递", "code": "chengda"},
  {"company": "城通物流", "code": "chengtong"},
  {"company": "法国大包、EMS-英文(Chronopost France)", "code": "chronopostfren"},
  {"company": "中国香港骏辉物流", "code": "chunfai"},
  {"company": "中骅物流", "code": "chunghwa56"},
  {"company": "泰国中通CTO", "code": "ctoexp"},
  {"company": "递达速运", "code": "didasuyun"},
  {"company": "易联通达", "code": "el56"},
  {"company": "澳州顺风快递", "code": "emms"},
  {"company": "乌克兰EMS(EMS Ukraine)", "code": "emsukraine"},
  {"company": "埃塞俄比亚(Ethiopian postal)", "code": "ethiopia"},
  {"company": "EU-EXPRESS", "code": "euexpress"},
  {"company": "易邮国际", "code": "euguoji"},
  {"company": "europeanecom", "code": "europeanecom"},
  {"company": "飞邦快递", "code": "fbkd"},
  {"company": "飞快达", "code": "feikuaida"},
  {"company": "全速快递", "code": "fsexp"},
  {"company": "安的快递", "code": "gda"},
  {"company": "容智快运", "code": "gdrz58"},
  {"company": "高捷快运", "code": "goldjet"},
  {"company": "航宇快递", "code": "hangyu"},
  {"company": "昊盛物流", "code": "haoshengwuliu"},
  {"company": "好来运", "code": "hlyex"},
  {"company": "顺时达物流", "code": "hnssd56"},
  {"company": "高铁速递", "code": "hre"},
  {"company": "华通快运", "code": "htongexpress"},
  {"company": "环东物流", "code": "huandonglg"},
  {"company": "汇强快递", "code": "huiqiangkuaidi"},
  {"company": "冰岛(Iceland Post)", "code": "iceland"},
  {"company": "大达物流", "code": "idada"},
  {"company": "多米尼加（INPOSDOM – Instituto Postal Dominicano）", "code": "inposdom"},
  {"company": "以色列(Israel Post)", "code": "israelpost"},
  {"company": "极光转运", "code": "jiguang"},
  {"company": "吉祥邮（澳洲）", "code": "jixiangyouau"},
  {"company": "哈萨克斯坦(Kazpost)", "code": "kazpost"},
  {"company": "KCS", "code": "kcs"},
  {"company": "科捷物流", "code": "kejie"},
  {"company": "快速递", "code": "ksudi"},
  {"company": "快达物流", "code": "kuaidawuliu"},
  {"company": "蓝镖快递", "code": "lanbiaokuaidi"},
  {"company": "老挝(Lao Express) ", "code": "lao"},
  {"company": "LaserShip", "code": "lasership"},
  {"company": "立白宝凯物流", "code": "lbbk"},
  {"company": "联邦快递-英文", "code": "lianbangkuaidien"},
  {"company": "鲁通快运", "code": "lutong"},
  {"company": "卢森堡(Luxembourg Post)", "code": "luxembourg"},
  {"company": "LWE", "code": "lwe"},
  {"company": "澳洲迈速快递", "code": "maxeedexpress"},
  {"company": "木春货运", "code": "mchy"},
  {"company": "墨西哥（Correos de Mexico）", "code": "mexico"},
  {"company": "民邦速递", "code": "minbangsudi"},
  {"company": "蒙古国(Mongol Post) ", "code": "mongolpost"},
  {"company": "阿曼(Oman Post)", "code": "oman"},
  {"company": "巴基斯坦(Pakistan Post)", "code": "pakistan"},
  {"company": "配思货运", "code": "peisihuoyunkuaidi"},
  {"company": "菲律宾（Philippine Postal）", "code": "phlpost"},
  {"company": "北极星快运", "code": "polarisexpress"},
  {"company": "坦桑尼亚（Tanzania Posts Corporation）", "code": "posta"},
  {"company": "急顺通", "code": "pzhjst"},
  {"company": "ANTS EXPRESS", "code": "qdants"},
  {"company": "全通快运", "code": "quantwl"},
  {"company": "荣庆物流", "code": "rokin"},
  {"company": "罗马尼亚（Posta Romanian）", "code": "romanian"},
  {"company": "日日通国际", "code": "rrthk"},
  {"company": "Safexpress", "code": "safexpress"},
  {"company": "塞尔维亚(PE Post of Serbia)", "code": "serbia"},
  {"company": "王牌快递", "code": "shipbyace"},
  {"company": "SHL畅灵国际物流", "code": "shlexp"},
  {"company": "顺捷达", "code": "shunjieda"},
  {"company": "中外运空运", "code": "sinoairinex"},
  {"company": "Siodemka", "code": "siodemka"},
  {"company": "申必达", "code": "speedoex"},
  {"company": "新速航", "code": "sunspeedy"},
  {"company": "黑猫宅急便", "code": "tcat"},
  {"company": "泰国中通ZTO", "code": "thaizto"},
  {"company": "天马迅达", "code": "tianma"},
  {"company": "Toll Priority(Toll Online)", "code": "tollpriority"},
  {"company": "通达兴物流", "code": "tongdaxing"},
  {"company": "通和天下", "code": "tonghetianxia"},
  {"company": "天使物流云", "code": "tswlcloud"},
  {"company": "邮鸽速运", "code": "ugoexpress"},
  {"company": "乌克兰小包、大包(UkrPoshta)", "code": "ukraine"},
  {"company": "乌克兰小包、大包(UkrPost)", "code": "ukrpost"},
  {"company": "UPS Freight", "code": "upsfreight"},
  {"company": "UPS Mail Innovations", "code": "upsmailinno"},
  {"company": "凡客配送（作废）", "code": "vancl"},
  {"company": "鹰运国际速递", "code": "vipexpress"},
  {"company": "香港伟豪国际物流", "code": "whgjkd"},
  {"company": "万邑通", "code": "winit"},
  {"company": "51跨境通", "code": "wykjt"},
  {"company": "先锋快递", "code": "xianfeng"},
  {"company": "一辉物流", "code": "yatfai"},
  {"company": "易通达", "code": "yitongda"},
  {"company": "一正达速运", "code": "yizhengdasuyun"},
  {"company": "运通快运", "code": "ytky168"},
  {"company": "元智捷诚", "code": "yuanzhijiecheng"},
  {"company": "运东西", "code": "yundx"},
  {"company": "珠峰速运", "code": "zf365"},
  {"company": "中环转运", "code": "zhonghuanus"},
  {"company": "忠信达", "code": "zhongxinda"},
  {"company": "准实快运", "code": "zsky123"},
  {"company": "澳多多国际速递", "code": "adodoxm"},
  {"company": "阿富汗(Afghan Post)", "code": "afghan"},
  {"company": "AFL", "code": "afl"},
  {"company": "全程快递", "code": "agopost"},
  {"company": "德方物流", "code": "ahdf"},
  {"company": "卡邦配送", "code": "ahkbps"},
  {"company": "无忧物流", "code": "aliexpress"},
  {"company": "亚马逊中国订单", "code": "amazoncnorder"},
  {"company": "amazon-国内订单", "code": "amcnorder"},
  {"company": "阿鲁巴[荷兰]（Post Aruba）", "code": "aruba"},
  {"company": "AUV国际快递", "code": "auvexpress"},
  {"company": "澳新物流", "code": "axexpress"},
  {"company": "阿塞拜疆EMS(EMS AzerExpressPost)", "code": "azerbaijan"},
  {"company": "巴林(Bahrain Post)", "code": "bahrain"},
  {"company": "孟加拉国(EMS)", "code": "bangladesh"},
  {"company": "宝通快递", "code": "baotongkd"},
  {"company": "报通快递", "code": "baoxianda"},
  {"company": "巴巴多斯(Barbados Post)", "code": "barbados"},
  {"company": "BCWELT", "code": "bcwelt"},
  {"company": "白俄罗斯(Belpochta)", "code": "belpost"},
  {"company": "笨鸟国际", "code": "benniao"},
  {"company": "邦工快运", "code": "bgky100"},
  {"company": "青云物流", "code": "bjqywl"},
  {"company": "鑫锐达", "code": "bjxsrd"},
  {"company": "BlueDart", "code": "bluedart"},
  {"company": "标杆物流", "code": "bmlchina"},
  {"company": "波黑(JP BH Posta)", "code": "bohei"},
  {"company": "玻利维亚", "code": "bolivia"},
  {"company": "BorderGuru", "code": "borderguru"},
  {"company": "博茨瓦纳", "code": "botspost"},
  {"company": "速方(Sufast)", "code": "bphchina"},
  {"company": "文莱(Brunei Postal)", "code": "brunei"},
  {"company": "新喀里多尼亚[法国](New Caledonia)", "code": "caledonia"},
  {"company": "仓鼠快递", "code": "cangspeed"},
  {"company": "Canpar", "code": "canpar"},
  {"company": "卢森堡航空", "code": "cargolux"},
  {"company": "钏博物流", "code": "cbo56"},
  {"company": "城铁速递", "code": "cex"},
  {"company": "昌宇国际", "code": "changwooair"},
  {"company": "SQK国际速递", "code": "chinasqk"},
  {"company": "同舟行物流", "code": "chinatzx"},
  {"company": "嘉荣物流", "code": "chllog"},
  {"company": "Chronopost Portugal", "code": "chronopostport"},
  {"company": "大韩通运", "code": "cjkoreaexpress"},
  {"company": "城晓国际快递", "code": "ckeex"},
  {"company": "CL日中速运", "code": "clsp"},
  {"company": "CNUP 中联邮", "code": "cnup"},
  {"company": "中国翼", "code": "cnws"},
  {"company": "哥伦比亚(4-72 La Red Postal de Colombia)", "code": "colombia"},
  {"company": "莫桑比克（Correios de Moçambique）", "code": "correios"},
  {"company": "阿根廷(Correo Argentina)", "code": "correoargentino"},
  {"company": "中远e环球", "code": "cosco"},
  {"company": "华中快递", "code": "cpsair"},
  {"company": "重庆星程快递", "code": "cqxingcheng"},
  {"company": "新时速物流", "code": "csxss"},
  {"company": "塞浦路斯(Cyprus Post)", "code": "cypruspost"},
  {"company": "云南诚中物流", "code": "czwlyn"},
  {"company": "达速物流", "code": "dasu"},
  {"company": "DCS", "code": "dcs"},
  {"company": "德国八易转运", "code": "deguo8elog"},
  {"company": "Deltec Courier", "code": "deltec"},
  {"company": "澳行快递", "code": "desworks"},
  {"company": "东风快递", "code": "dfkuaidi"},
  {"company": "达方物流", "code": "dfpost"},
  {"company": "dhl小包", "code": "dhlecommerce"},
  {"company": "DHL HK", "code": "dhlhk"},
  {"company": "DHL-荷兰（DHL Netherlands）", "code": "dhlnetherlands"},
  {"company": "DHL-波兰（DHL Poland）", "code": "dhlpoland"},
  {"company": "递五方云仓", "code": "di5pll"},
  {"company": "店通快递", "code": "diantongkuaidi"},
  {"company": "云南滇驿物流", "code": "dianyi"},
  {"company": "叮咚快递", "code": "dingdong"},
  {"company": "Direct Link", "code": "directlink"},
  {"company": "递四方澳洲", "code": "disifangau"},
  {"company": "递四方美国", "code": "disifangus"},
  {"company": "天翔东捷运", "code": "djy56"},
  {"company": "东瀚物流", "code": "donghanwl"},
  {"company": "东红物流", "code": "donghong"},
  {"company": "DTDC India", "code": "dtdcindia"},
  {"company": "东方航空物流", "code": "ealceair"},
  {"company": "EC-Firstclass", "code": "ecfirstclass"},
  {"company": "ECMS Express", "code": "ecmsglobal"},
  {"company": "东西E全运", "code": "ecotransite"},
  {"company": "厄瓜多尔(Correos del Ecuador)", "code": "ecuador"},
  {"company": "易达快运", "code": "edaeuexpress"},
  {"company": "益递物流", "code": "edlogistics"},
  {"company": "龙象国际物流", "code": "edragon"},
  {"company": "埃及（Egypt Post）", "code": "egypt"},
  {"company": "希腊包裹（ELTA Hellenic Post）", "code": "elta"},
  {"company": "高考通知书", "code": "emsluqu"},
  {"company": "南非EMS", "code": "emssouthafrica"},
  {"company": "乌克兰EMS-中文(EMS Ukraine)", "code": "emsukrainecn"},
  {"company": "英国(大包,EMS)", "code": "england"},
  {"company": "联众国际", "code": "epspost"},
  {"company": "Estafeta", "code": "estafeta"},
  {"company": "Estes", "code": "estes"},
  {"company": "中欧国际物流", "code": "eucnrail"},
  {"company": "德国 EUC POST", "code": "eucpost"},
  {"company": "败欧洲", "code": "europe8"},
  {"company": "可可树美中速运", "code": "excocotree"},
  {"company": "澳洲新干线快递", "code": "expressplus"},
  {"company": "易转运", "code": "ezhuanyuan"},
  {"company": "颿达国际快递-英文", "code": "fandaguoji"},
  {"company": "颿达国际快递", "code": "fardarww"},
  {"company": "速派快递", "code": "fastgoexpress"},
  {"company": "加拿大联通快运", "code": "fastontime"},
  {"company": "FedEx-英国件", "code": "fedexukcn"},
  {"company": "FedRoad 联邦转运", "code": "fedroad"},
  {"company": "飞狐快递", "code": "feihukuaidi"},
  {"company": "凤凰快递", "code": "fenghuangkuaidi"},
  {"company": "斐济(Fiji Post)", "code": "fiji"},
  {"company": "花瓣转运", "code": "flowerkd"},
  {"company": "飞力士物流", "code": "flysman"},
  {"company": "法翔速运", "code": "ftlexpress"},
  {"company": "飞云快递系统", "code": "fyex"},
  {"company": "甘肃安的快递", "code": "gansuandi"},
  {"company": "Gati-中文", "code": "gaticn"},
  {"company": "Gati-英文", "code": "gatien"},
  {"company": "Gati-KWE", "code": "gatikwe"},
  {"company": "广东诚通物流", "code": "gdct56"},
  {"company": "新鹏快递", "code": "gdxp"},
  {"company": "GE2D跨境物流", "code": "ge2d"},
  {"company": "环创物流", "code": "ghl"},
  {"company": "直布罗陀[英国]( Royal Gibraltar Post)", "code": "gibraltar"},
  {"company": "冠捷物流 ", "code": "gjwl"},
  {"company": "globaltracktrace", "code": "globaltracktrace"},
  {"company": "英脉物流", "code": "gml"},
  {"company": "UBI Australia", "code": "gotoubi"},
  {"company": "格陵兰[丹麦]（TELE Greenland A/S）", "code": "greenland"},
  {"company": "哥士传奇速递", "code": "gscq365"},
  {"company": "万通快递", "code": "gswtkd"},
  {"company": "GT国际快运", "code": "gtgogo"},
  {"company": "广通速递", "code": "gtongsudi"},
  {"company": "广东通路", "code": "guangdongtonglu"},
  {"company": "冠庭国际物流", "code": "guanting"},
  {"company": "国送快运", "code": "guosong"},
  {"company": "宏观国际快递", "code": "gvpexpress"},
  {"company": "贵州星程快递", "code": "gzxingcheng"},
  {"company": "海红for买卖宝", "code": "haihongmmb"},
  {"company": "海盟速递", "code": "haimengsudi"},
  {"company": "海星桥快递", "code": "haixingqiao"},
  {"company": "汉邦国际速递", "code": "handboy"},
  {"company": "好又快物流", "code": "haoyoukuai"},
  {"company": "开心快递", "code": "happylink"},
  {"company": "亚美尼亚(Haypost-Armenian Postal)", "code": "haypost"},
  {"company": "恒瑞物流", "code": "hengrui56"},
  {"company": "合心速递", "code": "hexinexpress"},
  {"company": "华瀚快递", "code": "hhair56"},
  {"company": "Highsince", "code": "highsince"},
  {"company": "黑狗物流", "code": "higo"},
  {"company": "海派通", "code": "hipito"},
  {"company": "猴急送", "code": "hjs"},
  {"company": "云邮跨境快递", "code": "hkems"},
  {"company": "互联快运", "code": "hlkytj"},
  {"company": "海联快递", "code": "hltop"},
  {"company": "飞鹰物流", "code": "hnfy"},
  {"company": "河南全速通", "code": "hnqst"},
  {"company": "居家通", "code": "homexpress"},
  {"company": "宏捷国际物流", "code": "hongjie"},
  {"company": "环球通达 ", "code": "hqtd"},
  {"company": "卓烨快递", "code": "hrbzykd"},
  {"company": "克罗地亚（Hrvatska Posta）", "code": "hrvatska"},
  {"company": "海硕高铁速递", "code": "hsgtsd"},
  {"company": "华通务达物流", "code": "htwd"},
  {"company": "华达快运", "code": "huada"},
  {"company": "辉联物流", "code": "huilian"},
  {"company": "驼峰国际", "code": "humpline"},
  {"company": "兰州伙伴物流", "code": "huoban"},
  {"company": "户通物流", "code": "hutongwuliu"},
  {"company": "鸿远物流", "code": "hyeship"},
  {"company": "上海昊宏国际货物", "code": "hyk"},
  {"company": "途鲜物流", "code": "ibenben"},
  {"company": "爱拜物流", "code": "ibuy8"},
  {"company": "iExpress", "code": "iexpress"},
  {"company": "logen路坚", "code": "ilogen"},
  {"company": "ILYANG", "code": "ilyang"},
  {"company": "Interlink Express", "code": "interlink"},
  {"company": "UPS i-parcel", "code": "iparcel"},
  {"company": "伊朗（Iran Post）", "code": "iran"},
  {"company": "爱尔兰(An Post)", "code": "ireland"},
  {"company": "Italy SDA", "code": "italysad"},
  {"company": "牙买加（Jamaica Post）", "code": "jamaicapost"},
  {"company": "jcex", "code": "jcex"},
  {"company": "嘉诚速达", "code": "jcsuda"},
  {"company": "骏达快递", "code": "jdexpressusa"},
  {"company": "JDIEX", "code": "jdiex"},
  {"company": "急递", "code": "jdpplus"},
  {"company": "泽西岛", "code": "jerseypost"},
  {"company": "佳家通货运", "code": "jiajiatong56"},
  {"company": "锦程物流", "code": "jinchengwuliu"},
  {"company": "劲通快递", "code": "jintongkd"},
  {"company": "晋越快递", "code": "jinyuekuaidi"},
  {"company": "九宫物流", "code": "jiugong"},
  {"company": "久易快递", "code": "jiuyicn"},
  {"company": "佳捷翔物流", "code": "jjx888"},
  {"company": "约旦(Jordan Post)", "code": "jordan"},
  {"company": "聚物物流", "code": "juwu"},
  {"company": "考拉国际速递", "code": "kaolaexpress"},
  {"company": "肯尼亚(POSTA KENYA)", "code": "kenya"},
  {"company": "嘉里大荣物流", "code": "kerrytj"},
  {"company": "柬埔寨中通", "code": "khzto"},
  {"company": "番薯国际货运", "code": "koali"},
  {"company": "淘韩国际快递", "code": "krtao"},
  {"company": "快8速运", "code": "kuai8"},
  {"company": "快淘快递", "code": "kuaitao"},
  {"company": "凯信达", "code": "kxda"},
  {"company": "吉尔吉斯斯坦(Kyrgyz Post)", "code": "kyrgyzpost"},
  {"company": "跨跃国际", "code": "kyue"},
  {"company": "蓝弧快递", "code": "lanhukuaidi"},
  {"company": "塞内加尔", "code": "laposte"},
  {"company": "林安物流", "code": "lasy56"},
  {"company": "乐递供应链", "code": "ledii"},
  {"company": "云豹国际货运", "code": "leopard"},
  {"company": "莱索托(Lesotho Post)", "code": "lesotho"},
  {"company": "美联快递", "code": "letseml"},
  {"company": "龙枫国际快递", "code": "lfexpress"},
  {"company": "联运快递", "code": "lianyun"},
  {"company": "黎巴嫩(Liban Post)", "code": "libanpost"},
  {"company": "丽狮物流", "code": "lishi"},
  {"company": "立陶宛（Lietuvos pa?tas）", "code": "lithuania"},
  {"company": "良藤国际速递", "code": "lmfex"},
  {"company": "隆浪快递", "code": "longlangkuaidi"},
  {"company": "长风物流", "code": "longvast"},
  {"company": "联通快递", "code": "ltparcel"},
  {"company": "蓝天国际快递", "code": "ltx"},
  {"company": "论道国际物流", "code": "lundao"},
  {"company": "马其顿(Macedonian Post)", "code": "macedonia"},
  {"company": "ME物流", "code": "macroexpressco"},
  {"company": "麦力快递", "code": "mailikuaidi"},
  {"company": "迈隆递运", "code": "mailongdy"},
  {"company": "马尔代夫(Maldives Post)", "code": "maldives"},
  {"company": "马耳他（Malta Post）", "code": "malta"},
  {"company": "芒果速递", "code": "mangguo"},
  {"company": "优能物流", "code": "mantoo"},
  {"company": "今枫国际快运", "code": "mapleexpress"},
  {"company": "美邦国际快递", "code": "meibang"},
  {"company": "美达快递", "code": "meidaexpress"},
  {"company": "Mexico Senda Express", "code": "mexicodenda"},
  {"company": "银河物流", "code": "milkyway"},
  {"company": "闽盛快递", "code": "minshengkuaidi"},
  {"company": "美龙快递", "code": "mjexp"},
  {"company": "摩尔多瓦(Posta Moldovei)", "code": "moldova"},
  {"company": "黑山(Posta Crne Gore)", "code": "montenegro"},
  {"company": "摩洛哥 ( Morocco Post )", "code": "morocco"},
  {"company": "魔速达", "code": "mosuda"},
  {"company": "MRW", "code": "mrw"},
  {"company": "Mexico Multipack", "code": "multipack"},
  {"company": "中俄速通（淼信）", "code": "mxe56"},
  {"company": "MyHermes", "code": "myhermes"},
  {"company": "纳米比亚(NamPost)", "code": "namibia"},
  {"company": "红马速递", "code": "nedahm"},
  {"company": "尼尔快递", "code": "nell"},
  {"company": "尼泊尔（Nepal Postal Services）", "code": "nepalpost"},
  {"company": "NLE", "code": "nle"},
  {"company": "华赫物流", "code": "nmhuahe"},
  {"company": "Nova Poshta", "code": "novaposhta"},
  {"company": "诺尔国际物流", "code": "nuoer"},
  {"company": "OBOR Express", "code": "oborexpress"},
  {"company": "OCA Argentina", "code": "ocaargen"},
  {"company": "OPEK", "code": "opek"},
  {"company": "中欧快运", "code": "otobv"},
  {"company": "波音速递", "code": "overseaex"},
  {"company": "巴拉圭(Correo Paraguayo)", "code": "paraguay"},
  {"company": "诚一物流", "code": "parcelchina"},
  {"company": "英国邮政大包EMS", "code": "parcelforcecn"},
  {"company": "全球速递", "code": "pdstow"},
  {"company": "派尔快递", "code": "peex"},
  {"company": "陪行物流", "code": "peixingwuliu"},
  {"company": "鹏程快递", "code": "pengcheng"},
  {"company": "鹏远国际速递", "code": "pengyuanexpress"},
  {"company": "秘鲁(SERPOST)", "code": "peru"},
  {"company": "皇家物流", "code": "pfcexpress"},
  {"company": "品速心达快递", "code": "pinsuxinda"},
  {"company": "先锋国际快递", "code": "pioneer"},
  {"company": "Portugal Seur", "code": "portugalseur"},
  {"company": "PostNord(Posten AB)", "code": "postenab"},
  {"company": "荷兰邮政-中国件", "code": "postnlchina"},
  {"company": "巴布亚新几内亚(PNG Post)", "code": "postpng"},
  {"company": "Purolator", "code": "purolator"},
  {"company": "7E速递", "code": "qesd"},
  {"company": "千里速递", "code": "qianli"},
  {"company": "卡塔尔（Qatar Post）", "code": "qpost"},
  {"company": "Quantium", "code": "quantium"},
  {"company": "全信通快递", "code": "quanxintong"},
  {"company": "全之鑫物流", "code": "qzx56"},
  {"company": "Red Express", "code": "redexpress"},
  {"company": "瑞丰速递", "code": "rfsd"},
  {"company": "rpx", "code": "rpx"},
  {"company": "日日顺快线", "code": "rrskx"},
  {"company": "捷网俄全通", "code": "ruexp"},
  {"company": "瑞达国际速递", "code": "ruidaex"},
  {"company": "全时速运", "code": "runhengfeng"},
  {"company": "卢旺达(Rwanda i-posita)", "code": "rwanda"},
  {"company": "日益通速递", "code": "rytsd"},
  {"company": "S2C", "code": "s2c"},
  {"company": "萨摩亚(Samoa Post)", "code": "samoa"},
  {"company": "三盛快递", "code": "sanshengco"},
  {"company": "沙特阿拉伯(Saudi Post)", "code": "saudipost"},
  {"company": "中加国际快递", "code": "scic"},
  {"company": "四川星程快递", "code": "scxingcheng"},
  {"company": "速呈", "code": "sczpds"},
  {"company": "泰国138国际物流", "code": "sd138"},
  {"company": "首达速运", "code": "sdsy888"},
  {"company": "优配速运", "code": "sdyoupei"},
  {"company": "Selektvracht", "code": "selektvracht"},
  {"company": "International Seur", "code": "seur"},
  {"company": "圣飞捷快递", "code": "sfjhd"},
  {"company": "盛丰物流", "code": "sfwl"},
  {"company": "衫达快运", "code": "shanda56"},
  {"company": "上海快通", "code": "shanghaikuaitong"},
  {"company": "上海无疆for买卖宝", "code": "shanghaiwujiangmmb"},
  {"company": "捎客物流", "code": "shaoke"},
  {"company": "盛通快递", "code": "shengtongscm"},
  {"company": "神马快递", "code": "shenma"},
  {"company": "苏豪快递", "code": "shipsoho"},
  {"company": "世运快递", "code": "shiyunkuaidi"},
  {"company": "wish邮", "code": "shpostwish"},
  {"company": "顺邦国际物流", "code": "shunbang"},
  {"company": "顺士达速运", "code": "shunshid"},
  {"company": "四海快递", "code": "sihaiet"},
  {"company": "四海捷运", "code": "sihiexpress"},
  {"company": "中外运速递-中文", "code": "sinoex"},
  {"company": "易普递", "code": "sixroad"},
  {"company": "skynet", "code": "skynet"},
  {"company": "SkyNet Malaysia", "code": "skynetmalaysia"},
  {"company": "荷兰Sky Post", "code": "skypost"},
  {"company": "斯洛伐克(Slovenská Posta)", "code": "slovak"},
  {"company": "斯洛文尼亚(Slovenia Post)", "code": "slovenia"},
  {"company": "斯里兰卡(Sri Lanka Post)", "code": "slpost"},
  {"company": "嗖一下同城快递", "code": "sofast56"},
  {"company": "行必达", "code": "speeda"},
  {"company": "首通快运", "code": "staky"},
  {"company": "星速递", "code": "starex"},
  {"company": "星运快递", "code": "staryvr"},
  {"company": "速呈宅配", "code": "sucheng"},
  {"company": "特急便物流", "code": "sucmj"},
  {"company": "苏丹（Sudapost）", "code": "sudapost"},
  {"company": "速配欧翼", "code": "superoz"},
  {"company": "速品快递", "code": "supinexpress"},
  {"company": "Sureline冠泰", "code": "sureline"},
  {"company": "狮爱高铁物流", "code": "sycawl"},
  {"company": "深圳DPEX", "code": "szdpex"},
  {"company": "天美快递", "code": "taimek"},
  {"company": "坦桑尼亚(Tanzania Posts)", "code": "tanzania"},
  {"company": "淘布斯国际物流", "code": "taoplus"},
  {"company": "TCI XPS", "code": "tcixps"},
  {"company": "TCXB国际物流", "code": "tcxbthai"},
  {"company": "天翔快递", "code": "tianxiang"},
  {"company": "天纵物流", "code": "tianzong"},
  {"company": "万家通快递", "code": "timedg"},
  {"company": "天联快运", "code": "tlky"},
  {"company": "TNT Italy", "code": "tntitaly"},
  {"company": "TNT Post", "code": "tntpostcn"},
  {"company": "TNY物流", "code": "tny"},
  {"company": "Toll", "code": "toll"},
  {"company": "顶世国际物流", "code": "topshey"},
  {"company": "突尼斯EMS(Rapid-Poste)", "code": "tunisia"},
  {"company": "德国优拜物流", "code": "ubuy"},
  {"company": "乌干达(Posta Uganda)", "code": "uganda"},
  {"company": "UTAO优到", "code": "utaoscm"},
  {"company": "瓦努阿图(Vanuatu Post)", "code": "vanuatu"},
  {"company": "越南小包(Vietnam Posts)", "code": "vietnam"},
  {"company": "维普恩物流", "code": "vps"},
  {"company": "万博快递", "code": "wanboex"},
  {"company": "豌豆物流", "code": "wandougongzhu"},
  {"company": "宁夏万家通", "code": "wanjiatong"},
  {"company": "万达美", "code": "wdm"},
  {"company": "未来明天快递", "code": "weilaimingtian"},
  {"company": "文捷航空", "code": "wenjiesudi"},
  {"company": "凡仕特物流", "code": "wlfast"},
  {"company": "WTD海外通", "code": "wtdex"},
  {"company": "温通物流", "code": "wto56kj"},
  {"company": "伍圆速递", "code": "wuyuansudi"},
  {"company": "微转运", "code": "wzhaunyun"},
  {"company": "西安胜峰", "code": "xaetc"},
  {"company": "国晶物流", "code": "xdshipping"},
  {"company": "西安城联速递", "code": "xianchengliansudi"},
  {"company": "湘达物流", "code": "xiangdawuliu"},
  {"company": "翔腾物流", "code": "xiangteng"},
  {"company": "小C海淘", "code": "xiaocex"},
  {"company": "西安喜来快递", "code": "xilaikd"},
  {"company": "新宁物流", "code": "xinning"},
  {"company": "信天捷快递", "code": "xintianjie"},
  {"company": "西邮寄", "code": "xipost"},
  {"company": "西游寄", "code": "xiyoug"},
  {"company": "鑫世锐达", "code": "xsrd"},
  {"company": "乾坤物流", "code": "yatexpress"},
  {"company": "YCG物流", "code": "ycgglobal"},
  {"company": "也门(Yemen Post)", "code": "yemen"},
  {"company": "宇航通物流", "code": "yhtlogistics"},
  {"company": "驿递汇速递", "code": "yidihui"},
  {"company": "宜送物流", "code": "yiex"},
  {"company": "艺凡快递", "code": "yifankd"},
  {"company": "易航物流", "code": "yihangmall"},
  {"company": "亿领速运", "code": "yilingsuyun"},
  {"company": "音素快运", "code": "yinsu"},
  {"company": "一柒国际物流", "code": "yiqiguojiwuliu"},
  {"company": "一起送", "code": "yiqisong"},
  {"company": "宜送", "code": "yisong"},
  {"company": "易邮速运", "code": "yiyou"},
  {"company": "洋口岸", "code": "ykouan"},
  {"company": "永邦国际物流", "code": "yongbangwuliu"},
  {"company": "永旺达快递", "code": "yongwangda"},
  {"company": "邮邦国际", "code": "youban"},
  {"company": "邮来速递", "code": "youlai"},
  {"company": "雅澳物流", "code": "yourscm"},
  {"company": "壹品速递", "code": "ypsd"},
  {"company": "粤中国际货运代理（上海）有限公司", "code": "yuezhongsh"},
  {"company": "煜嘉物流", "code": "yujiawuliu"},
  {"company": "韵丰物流", "code": "yunfeng56"},
  {"company": "YUN TRACK", "code": "yuntrack"},
  {"company": "燕文物流", "code": "yw56"},
  {"company": "远为快递", "code": "ywexpress"},
  {"company": "西安运逸快递", "code": "yyexp"},
  {"company": "一运全成物流", "code": "yyqc56"},
  {"company": "亚洲顺物流", "code": "yzswuliu"},
  {"company": "三三国际物流", "code": "zenzen"},
  {"company": "众辉达物流", "code": "zhdwl"},
  {"company": "志腾物流", "code": "zhitengwuliu"},
  {"company": "中睿速递", "code": "zhongruisudi"},
  {"company": "众派速递", "code": "zhpex"},
  {"company": "卓实快运", "code": "zhuoshikuaiyun"},
  {"company": "振捷国际货运", "code": "zjgj56"},
  {"company": "青旅物流", "code": "zqlwl"},
  {"company": "转瞬达集运", "code": "zsda56"},
  {"company": "明辉物流", "code": "zsmhwl"},
  {"company": "智通物流", "code": "ztong"},

]
